### ISSUE TITLE
8.8.20.1-Stay-On-Topic

### ISSUE THREAD

**Issue by Imbaker1234** [object-Object/GuildBot#4]
**As a** Trustee

**I want to** quickly repost the channel topic with a simple command

**In order to** promote channels staying true to their purpose

> **Acceptance Criteria**
> Implement a short command, for example `!topic` which will fetch the topic from the channel in which it is executed. Then repost that topic in an embed. Perhaps with the title **This Channel is For** or **The Purpose of this Channel**.

**Comment by Imbaker1234** [comment]
I'd like to avoid any plaintext responses from the bot in production. It looks low brow and tacky. It takes very little additional effort to plug it into a simple embed.

**Comment by object-Object** [comment]
Agreed - plaintext should only be used if we want to mention someone

**Comment by object-Object** [comment]
Implemented in https://github.com/object-Object/GuildBot/commit/d3a78fc5aa401bdf02d9711128ba61432a3be6af
